Lab 1
Bazalii/OOP-labs pull request #2
Opened 2021-09-16 21:22 UTC by Bazalii

2021-09-20 17:07 UTC, whytrall requested changes
Пока поверхностное ревью, с точки зрения ООП позже гляну

2021-10-02 16:05 UTC, annchous requested changes
Сущности перенести в папку Entities, потому что они - не сервисы.

2021-10-03 12:20 UTC, annchous requested changes

2021-10-03 20:02 UTC, annchous requested changes

2021-10-06 06:51 UTC, annchous approved these changes

2021-10-07 10:10 UTC, merged